blank_issues_enabled: false
contact_links:
  - name: Questions & Support
    url: https://discord.gg/MUSdsS
    about: We don't offer official support - only community support. Join our 24/7 Discord server and post your question there, we've a great community growing, that are happy to help.
